language: python
python:
  - "3.2"
jdk:
  - oraclejdk7
env:
 global:
  - "ARTIFACTS_AWS_REGION=eu-west-1"
  - "ARTIFACTS_S3_BUCKET=ingress-apk-mod"
  - secure: "R8NVyaL8GRIes8z487YQvOTEnd/kCIgzJ/3daqsIRoL67RbHdI7T+EPgMKWm2WPq17E9iFHfXgbhctNDXHItN7xk14SdeVZp6zVIyUyPWDkjBnayEdEnTi/iu4uWt5yXAj85jxTicVttju/Wnc04fw/vEWCHyMpZk8XK8K28xFg="
  - secure: "oGuAbtcKuPyiqhzV0J+EAmDpEqUvgOpg321CvWN9SxVKSlgnakjfWrHSvwjALzPqI+lPeiw9m/ht4APPqqRU6rfMSwAEvj6SSqNi++jqixl6etessSmyovtPCSxK7HWOgY68nKjSR9gJOHIyYwWdTasJ0FSzRAPik5zd29mnn+0="
before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget -O android-sdk-linux.tgz http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz
  - tar -zxf android-sdk-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/17.0.0/:${ANDROID_HOME}/tools/proguard/bin/
  - echo y | android update sdk --filter android-17,platform-tools,build-tools-17.0.0 --all --no-ui --force
  - wget --no-check-certificate https://dl.dropboxusercontent.com/u/4976322/ingress/lib.tar.gz
  - tar xvfz lib.tar.gz
  - wget --no-check-certificate https://dl.dropboxusercontent.com/u/4976322/ingress/apk/ingress-latest.apk
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - "gem install travis-artifacts"
script:
  - git config --global user.email ""
  - git config --global user.name "Ingress apk mod"
  - python bin/import_apk.py ingress-latest.apk
  - python bin/release.py
after_success:
  - "travis-artifacts upload --path release/ingress-latest-broot-*.apk --target-path builds"
  - "travis-artifacts upload --path release/ingress-latest-broot-*-mute.apk --target-path builds"
notifications:
  email:
    on_success: never
